global:
  scrape_interval:     15s 
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus_first'

    
    scrape_interval: 5s

    static_configs:
      - targets: ['host.docker.internal:5000']